name = "helicone-worker-dev"
main = "src/index.ts"
compatibility_date = "2022-11-29"
compatibility_flags = [
	"transformstream_enable_standard_constructor",
	"streams_enable_constructors",
]
logpush = true
node_compat = true

durable_objects.bindings = [
	{ name = "RATE_LIMITER", class_name = "AtomicRateLimiter" }
]

kv_namespaces = [
	{ binding = "RATE_LIMIT_KV", id = "a0c7e405b97a4e058d7d77293de97c48"},
	{ binding = "CACHE_KV", id = "282ec0c15fd649929f7209214f7ac7a4"},
	{ binding = "INSERT_KV", id = "246e15717ba3497189cc1e1694a90987"},
	{ binding = "UTILITY_KV", id = "8e4fdc62d7fd4b8bbf4430f5d1b7a23b"},
	{ binding = "REQUEST_AND_RESPONSE_QUEUE_KV", id = "f44218adb1f94c879c7a1597ecbc387f"},
	{ binding = "SECURE_CACHE", id = "82b1b0b19a7247c4a0f0c62faf6353da" },
]

[vars]
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU"
SUPABASE_URL = "http://localhost:54321"
CLICKHOUSE_HOST = "http://localhost:18123"
CLICKHOUSE_USER = "default"
CLICKHOUSE_PASSWORD = ""
PROVIDER = "OPENAI"
TOKEN_COUNT_URL = "https://tokens.helicone.ai/anthropic/count_tokens"
WORKER_TYPE = "OPENAI_PROXY"
VAULT_ENABLED = "true"
REQUEST_CACHE_KEY = "9984c295ec7d0f506b8af65e9d60773480eb0c9347a6bd8a2b08fb57b5117701"
VALHALLA_URL = "http://localhost:8585"

[triggers]
crons = ["* * * * *", "0 * * * *"]

[env.production]
name = "helicone-worker-prod"
routes = [
	{ pattern = "oai.hconeai.com", custom_domain = true, zone_name = "hconeai.com" },
	{ pattern = "anthropic.hconeai.com", custom_domain = true, zone_name = "hconeai.com" },
	{ pattern = "api.hconeai.com", custom_domain = true, zone_name = "hconeai.com" },
	{ pattern = "gateway.hconeai.com", custom_domain = true, zone_name = "hconeai.com" },
	{ pattern = "2yfv.hconeai.com", custom_domain = true, zone_name = "hconeai.com" },
]

durable_objects.bindings = [
	{ name = "RATE_LIMITER", class_name = "AtomicRateLimiter" }
]

kv_namespaces = [
	{ binding = "RATE_LIMIT_KV", id = "a0c7e405b97a4e058d7d77293de97c48"},
	{ binding = "CACHE_KV", id = "282ec0c15fd649929f7209214f7ac7a4"},
	{ binding = "INSERT_KV", id = "246e15717ba3497189cc1e1694a90987"},
	{ binding = "UTILITY_KV", id = "8e4fdc62d7fd4b8bbf4430f5d1b7a23b"},
	{ binding = "REQUEST_AND_RESPONSE_QUEUE_KV", id = "f44218adb1f94c879c7a1597ecbc387f"},
	{ binding = "SECURE_CACHE", id = "82b1b0b19a7247c4a0f0c62faf6353da" },
]

[env.production.triggers]
crons = ["* * * * *", "0 * * * *"]

queues.producers = [
	{ binding = "FALLBACK_QUEUE", queue = "fallback-queue-prod" },
]

[env.production.vars]
SUPABASE_URL = "https://bolqqmqbrciybnypvklh.supabase.co"
CLICKHOUSE_HOST = "https://p76qbrlulo.us-east-1.aws.clickhouse.cloud:8443"
CLICKHOUSE_USER = "default"
VAULT_ENABLED = "true"


[env.production_staging]
name = "helicone-worker-prod-staging"
routes = [
	{ pattern = "oai_staging.hconeai.com", custom_domain = true, zone_name = "hconeai.com" },
	{ pattern = "anthropic_staging.hconeai.com", custom_domain = true, zone_name = "hconeai.com" },
	{ pattern = "api_staging.hconeai.com", custom_domain = true, zone_name = "hconeai.com" },
	{ pattern = "gateway_staging.hconeai.com", custom_domain = true, zone_name = "hconeai.com" },
	{ pattern = "2yfv_staging.hconeai.com", custom_domain = true, zone_name = "hconeai.com" },
	{ pattern = "2yfv_staging2.hconeai.com", custom_domain = true, zone_name = "hconeai.com" },
]

kv_namespaces = [
	{ binding = "RATE_LIMIT_KV", id = "a0c7e405b97a4e058d7d77293de97c48"},
	{ binding = "CACHE_KV", id = "282ec0c15fd649929f7209214f7ac7a4"},
	{ binding = "INSERT_KV", id = "246e15717ba3497189cc1e1694a90987"},
	{ binding = "UTILITY_KV", id = "8e4fdc62d7fd4b8bbf4430f5d1b7a23b"},
	{ binding = "REQUEST_AND_RESPONSE_QUEUE_KV", id = "f44218adb1f94c879c7a1597ecbc387f"},
	{ binding = "SECURE_CACHE", id = "82b1b0b19a7247c4a0f0c62faf6353da" },
]

durable_objects.bindings = [
	{ name = "RATE_LIMITER", class_name = "AtomicRateLimiter" }
]

queues.producers = [
	{ binding = "FALLBACK_QUEUE", queue = "fallback-queue-staging" },
]

[env.production_staging.vars]
SUPABASE_URL = "https://bolqqmqbrciybnypvklh.supabase.co"
CLICKHOUSE_HOST = "https://p76qbrlulo.us-east-1.aws.clickhouse.cloud:8443"
CLICKHOUSE_USER = "default"
VAULT_ENABLED = "true"


[[migrations]]
tag = "v1"
new_classes = ["AtomicRateLimiter"]